#### Imports

In [122]:
import pandas as pd
import torch
import numpy as np
import os
from sklearn.model_selection import train_test_split
from sklearn.utils.class_weight import compute_class_weight
from datasets import Dataset
from huggingface_hub import login
import logging
from transformers import (
    TrainingArguments,
    Trainer,
    AutoModelForSequenceClassification,
    # tokenizers
    AutoTokenizer,
    DebertaV2Tokenizer,
    DistilBertTokenizer,
    BertTokenizer,
    RobertaTokenizer,
    ElectraTokenizer,
    AlbertTokenizer,
    XLNetTokenizer,
    MobileBertTokenizer,
    # models
    DebertaV2ForSequenceClassification,
    DistilBertForSequenceClassification,
    BertForSequenceClassification,
    RobertaForSequenceClassification,
    ElectraForSequenceClassification,
    AlbertForSequenceClassification,
    XLNetForSequenceClassification,
    MobileBertForSequenceClassification,
)
from torch.nn import CrossEntropyLoss
# evaluation metrics
from sklearn.metrics import accuracy_score, precision_recall_fscore_support, classification_report
from collections import Counter

import transformers
print(transformers.__version__)
print(transformers.TrainingArguments)

# Cuda
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

4.57.3
<class 'transformers.training_args.TrainingArguments'>

In [123]:
logging.basicConfig(filename='classification.log', level=logging.INFO)
logging.info(f"Running on device: {device}")

In [124]:
# setting huggingface token
login(token=os.getenv("HUGGINGFACE_TOKEN"))

os.environ["HF_HOME"] = "D:/huggingface_cache" 
os.environ["TRANSFORMERS_CACHE"] = "D:/huggingface_cache"
os.environ["HUGGINGFACE_HUB_CACHE"] = "D:/huggingface_cache"

print("HF_HOME:", os.getenv("HF_HOME"))
print("TRANSFORMERS_CACHE:", os.getenv("TRANSFORMERS_CACHE"))
print("HUGGINGFACE_HUB_CACHE:", os.getenv("HUGGINGFACE_HUB_CACHE"))

logging.info(f"HF_HOME: {os.getenv('HF_HOME')}")
logging.info(f"TRANSFORMERS_CACHE: {os.getenv('TRANSFORMERS_CACHE')}")
logging.info(f"HUGGINGFACE_HUB_CACHE: {os.getenv('HUGGINGFACE_HUB_CACHE')}")

transformers.utils.hub.TRANSFORMERS_CACHE = "D:/huggingface_cache"

HF_HOME: D:/huggingface_cache
TRANSFORMERS_CACHE: D:/huggingface_cache
HUGGINGFACE_HUB_CACHE: D:/huggingface_cache

### LOADING SQLITE DB WITH RECORDS

In [125]:
import sqlite3
import json
import pandas as pd

DB_FILE = "chunks.db"
OUTPUT_FILE = "exported_chunks.jsonl"

# Connect to the database
conn = sqlite3.connect(DB_FILE)
cur = conn.cursor()

# Query all data from chunks table
cur.execute("SELECT text, label FROM chunks")
rows = cur.fetchall()

# Write to JSONL
with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
    for text, label in rows:
        obj = {"text": text}
        if label is not None:
            obj["label"] = label
        f.write(json.dumps(obj) + "\n")

conn.close()

print("Data exported to JSONL file.")

Data exported to JSONL file.

In [126]:
# Load the labeled chunks
with open("exported_chunks.jsonl", "r", encoding="utf-8") as f:
    labeled_chunks = [json.loads(line) for line in f]

data = pd.DataFrame(labeled_chunks)
labeled_count = data['label'].value_counts().to_dict()

# Get the first 9000 rows
data = data.head(9000)

# Remove rows with label == 11
data = data[data['label'] != 11]

# Print labeled count after removing label 11
labeled_count = data['label'].value_counts().to_dict()
print(f"Labeled chunks after removing label 11: {labeled_count}")

# Remove rows where label == 1 and text length < 100
data = data[~((data['label'] == 1) & (data['text'].str.len() < 100))]

# Keep only chunks with at least MIN_CHUNK_TOKENS (tokenizer-based)
MIN_CHUNK_TOKENS = 20
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
data = data[data["text"].apply(lambda t: len(tokenizer.encode(t, truncation=True, max_length=512)) >= MIN_CHUNK_TOKENS)]

# Print final labeled count
labeled_count = data['label'].value_counts().to_dict()
print(f"Final labeled chunks (after >= {MIN_CHUNK_TOKENS} token cutoff): {labeled_count}")

Labeled chunks after removing label 11: {1: 5465, 0: 3535}
Final labeled chunks (after >= 20 token cutoff): {1: 4681, 0: 1635}

##### Spliting data

In [127]:
# Loading the data
data['label'] = data['label'].astype(int)

# Train-Test Split using stratified sampling
train_df, test_df = train_test_split(data, test_size=0.2, stratify=data['label'], random_state=42)

# since there is a class imbalance, we will compute class weights
# to handle this in the loss function
labels = train_df["label"].values
# Compute class weights
classes = np.unique(labels)
weights = compute_class_weight(class_weight="balanced",
                            classes=classes,
                            y=labels)
class_weights = torch.tensor(weights, dtype=torch.float, device=device)
print("Class weights:", class_weights)

# Convert ing the DataFrames to Hugging Face Datasets
train_dataset = Dataset.from_pandas(train_df.reset_index(drop=True))
test_dataset = Dataset.from_pandas(test_df.reset_index(drop=True))

Class weights: tensor([1.9312, 0.6747], device='cuda:0')

In [128]:
# ---- Tuning parameters ----
# Size tiers and LRs follow convention from: Devlin et al. 2019 (BERT), Mosbach et al. 2021 (fine-tuning stability).
# Small <100M, Base/Medium ~110M, Large 300M+. Larger models use slightly lower LR for stable convergence.
CONFIG = {
    # epochs tuned by model size/type
    "epochs": 3,
    # batch sizes tuned by model size/type
    "batch_size": {
        "small": 16,
        "medium": 8,
        "large": 4
    },
    "max_length": [128, 256, 512],  # Max length of input sequences
    # learning rates by size (small -> higher, large -> lower; Devlin et al. 2e-5--5e-5)
    "learning_rate": {
        "small": 5e-5,
        "medium": 3e-5,
        "large": 2e-5
    },
    "weight_decay": 0.01,  # Weight decay for regularization
    "output_dir": "D:/huggingface_cache/classification_models"
}

# ---- Model configurations ----
# Ordered roughly by parameter count (small -> xxl). Each model has a 'type' key.
MODEL_CONFIGS = {
    # ---- XS (very small, <= ~20M) ----
    "albert-base-v2": {
        "type": "small",
        "tokenizer_class": AlbertTokenizer,
        "pretrained_model_name": "albert-base-v2",  # ~11M
        "model_class": AlbertForSequenceClassification
    },
    "electra-small": {
        "type": "small",
        "tokenizer_class": ElectraTokenizer,
        "": "google/electra-small-discriminator",  # ~14M
        "model_class": ElectraForSequenceClassification
    },
    # ---- S (small, ~20M-70M) ----
    "mobilebert": {
        "type": "small",
        "tokenizer_class": AutoTokenizer,
        "pretrained_model_name": "google/mobilebert-uncased",  # ~25M
        "model_class": MobileBertForSequenceClassification
    },
    "deberta-v3-small": {
        "type": "small",
        "tokenizer_class": DebertaV2Tokenizer,
        "pretrained_model_name": "microsoft/deberta-v3-small",  # ~55M
        "model_class": DebertaV2ForSequenceClassification
    },
    "distilbert": {
        "type": "small",
        "tokenizer_class": DistilBertTokenizer,
        "pretrained_model_name": "distilbert-base-uncased",  # ~66M
        "model_class": DistilBertForSequenceClassification
    },

    # ---- M (medium, ~70M-200M) ----
    "bert": {
        "type": "medium",
        "tokenizer_class": BertTokenizer,
        "pretrained_model_name": "bert-base-uncased",  # ~110M
        "model_class": BertForSequenceClassification
    },
    "xlnet": {
        "type": "medium",
        "tokenizer_class": XLNetTokenizer,
        "pretrained_model_name": "xlnet-base-cased",  # ~110M
        "model_class": XLNetForSequenceClassification
    },
    "roberta": {
        "type": "medium",
        "tokenizer_class": RobertaTokenizer,
        "pretrained_model_name": "roberta-base",  # ~125M
        "model_class": RobertaForSequenceClassification
    },
     # ---- Mid-range / other configs kept (type inferred) ----
    "deberta-v3-base": {
        "type": "medium",
        "tokenizer_class": AutoTokenizer,
        "pretrained_model_name": "microsoft/deberta-v3-base", # ~140M
        "model_class": AutoModelForSequenceClassification
    },
    "xlm-roberta-base": {
        "type": "medium",
        "tokenizer_class": AutoTokenizer,
        "pretrained_model_name": "xlm-roberta-base",  # ~270M
        "model_class": AutoModelForSequenceClassification
    },
    "bert-large-uncased": {
        "type": "large",
        "tokenizer_class": BertTokenizer,
        "pretrained_model_name": "bert-large-uncased",  # ~340M
        "model_class": BertForSequenceClassification
    },
    "roberta-large": {
        "type": "large",
        "tokenizer_class": RobertaTokenizer,
        "pretrained_model_name": "roberta-large",  # ~355M
        "model_class": RobertaForSequenceClassification
    },
    "electra-large": {
        "type": "large",
        "tokenizer_class": ElectraTokenizer,
        "pretrained_model_name": "google/electra-large-discriminator",  # ~335M
        "model_class": ElectraForSequenceClassification
    },
    # ---- XL (extra large, ~400M-800M) ----
    "xlm-roberta-large": {
        "type": "large",
        "tokenizer_class": AutoTokenizer,
        "pretrained_model_name": "xlm-roberta-large",  # ~550M
        "model_class": AutoModelForSequenceClassification
    },
    # ---- XXL (very large, > ~800M) ----
    "deberta-large": {
        "type": "large",
        "tokenizer_class": AutoTokenizer,
        "pretrained_model_name": "microsoft/deberta-large",  # very large (~>800M depending on variant)
        "model_class": AutoModelForSequenceClassification
    }
}

In [129]:

# ---- Metric function ----
def compute_metrics(pred):
    labels = pred.label_ids
    preds = pred.predictions.argmax(-1)
    precision, recall, f1, _ = precision_recall_fscore_support(labels, preds, average='weighted')
    acc = accuracy_score(labels, preds)
    return {'accuracy': acc, 'f1': f1, 'precision': precision, 'recall': recall}

In [130]:
# ---- Weighted Trainer ----
class WeightedLossTrainer(Trainer):
    def __init__(self, class_weights=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.class_weights = class_weights

    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        labels = inputs.get("labels")
        outputs = model(**inputs)
        logits = outputs.get("logits")
        loss_fct = CrossEntropyLoss(weight=self.class_weights)
        loss = loss_fct(logits, labels)
        return (loss, outputs) if return_outputs else loss

In [131]:

# ---- Function to train and evaluate ----
def train_and_evaluate(model_name, train_dataset, test_dataset, data, max_length):
    print(f"\n===== Training {model_name} =====")

    # Model + tokenizer
    cfg = MODEL_CONFIGS[model_name]
    tokenizer = cfg["tokenizer_class"].from_pretrained(cfg["pretrained_model_name"])
    model = cfg["model_class"].from_pretrained(
        cfg["pretrained_model_name"],
        num_labels=len(data['label'].unique())
    )

    # Tokenization
    def tokenize_fn(batch):
        return tokenizer(batch["text"], truncation=True, padding="max_length", max_length=max_length)

    train_enc = train_dataset.map(tokenize_fn, batched=True)
    test_enc = test_dataset.map(tokenize_fn, batched=True)
    train_enc = train_enc.rename_column("label", "labels")
    test_enc = test_enc.rename_column("label", "labels")
    train_enc.set_format(type="torch", columns=["input_ids", "attention_mask", "labels"])
    test_enc.set_format(type="torch", columns=["input_ids", "attention_mask", "labels"])

    # Training args (LR by size; warmup per Mosbach et al. 2021)
    training_args = TrainingArguments(
        output_dir=f"{CONFIG['output_dir']}/{model_name}",
        eval_strategy="epoch",
        save_strategy="epoch",
        learning_rate=CONFIG["learning_rate"][cfg["type"]],
        per_device_train_batch_size=CONFIG["batch_size"][cfg["type"]],
        per_device_eval_batch_size=CONFIG["batch_size"][cfg["type"]],
        num_train_epochs=CONFIG["epochs"],
        weight_decay=CONFIG["weight_decay"],
        warmup_ratio=0.1,
        logging_dir=f"./logs_{model_name}",
        report_to="none",
        load_best_model_at_end=True,
        metric_for_best_model="f1",
        seed=42
    )

    # Trainer
    trainer = WeightedLossTrainer(
        model=model,
        args=training_args,
        train_dataset=train_enc,
        eval_dataset=test_enc,
        compute_metrics=compute_metrics,
        tokenizer=tokenizer,
        class_weights=class_weights
    )

    # Train + evaluate
    # time to train
    t_train_start = torch.cuda.Event(enable_timing=True)
    t_train_end = torch.cuda.Event(enable_timing=True)
    t_train_start.record()
    trainer.train()
    t_train_end.record()
    torch.cuda.synchronize()
    t_train_time = t_train_start.elapsed_time(t_train_end) / 1000  # convert to seconds
    print(f"Training time for {model_name}: {t_train_time:.2f} seconds")
    
    # Get best checkpoint
    best_checkpoint = trainer.state.best_model_checkpoint
    print(f"Best checkpoint for {model_name}: {best_checkpoint}")

    # Predictions
    t_pred_start = torch.cuda.Event(enable_timing=True)
    t_pred_end = torch.cuda.Event(enable_timing=True)
    t_pred_start.record()
    preds = trainer.predict(test_enc)
    t_pred_end.record()
    torch.cuda.synchronize()
    t_pred_time = t_pred_start.elapsed_time(t_pred_end) / 1000  # convert to seconds
    print(f"Prediction time for {model_name}: {t_pred_time:.2f} seconds")
    y_true = preds.label_ids
    y_pred = np.argmax(preds.predictions, axis=1)

    print(f"\nClassification Report for {model_name}:")
    print(classification_report(y_true, y_pred, digits=4))

    performance = {
        "model": model_name,
        "max_length": max_length,
        "train_time_sec": t_train_time,
        "pred_time_sec": t_pred_time,
        "best_checkpoint": best_checkpoint,
        "accuracy": accuracy_score(y_true, y_pred),
        "f1": precision_recall_fscore_support(y_true, y_pred, average='weighted')[2],
        "precision": precision_recall_fscore_support(y_true, y_pred, average='weighted')[0],
        "recall": precision_recall_fscore_support(y_true, y_pred, average='weighted')[1],
    }
    return performance

In [132]:
existing_results = pd.DataFrame()
if os.path.exists("model_performance.csv"):
    existing_results = pd.read_csv("model_performance.csv")

for model_name in MODEL_CONFIGS.keys():
    for max_len in CONFIG["max_length"]:
        if not existing_results.empty and len(existing_results[(existing_results['model'] == model_name) & (existing_results['max_length'] == max_len)]) > 0:
            print(f"Skipping {model_name} with max_length={max_len} (already in CSV).")
            continue

        print(f"\n--- Training {model_name} with max_length={max_len} ---")
        performance = train_and_evaluate(model_name, train_dataset, test_dataset, data, max_len)
        print(performance)
        # save performance to a csv file (used by statistical-test.ipynb)
        with open("model_performance.csv", "a") as f:
            # headers if file is empty
            if os.stat("model_performance.csv").st_size == 0:
                f.write("model,max_length,train_time_sec,pred_time_sec,best_checkpoint,accuracy,f1,precision,recall\n")
            f.write(",".join([str(performance[k]) for k in performance]) + "\n")

Skipping albert-base-v2 with max_length=128 (already in CSV).
Skipping albert-base-v2 with max_length=256 (already in CSV).
Skipping albert-base-v2 with max_length=512 (already in CSV).
Skipping electra-small with max_length=128 (already in CSV).
Skipping electra-small with max_length=256 (already in CSV).
Skipping electra-small with max_length=512 (already in CSV).
Skipping mobilebert with max_length=128 (already in CSV).
Skipping mobilebert with max_length=256 (already in CSV).
Skipping mobilebert with max_length=512 (already in CSV).
Skipping deberta-v3-small with max_length=128 (already in CSV).
Skipping deberta-v3-small with max_length=256 (already in CSV).
Skipping deberta-v3-small with max_length=512 (already in CSV).
Skipping distilbert with max_length=128 (already in CSV).
Skipping distilbert with max_length=256 (already in CSV).
Skipping distilbert with max_length=512 (already in CSV).

--- Training bert with max_length=128 ---

===== Training bert =====

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Map:   0%|          | 0/5052 [00:00<?, ? examples/s]

Map:   0%|          | 0/1264 [00:00<?, ? examples/s]

C:\Users\ctngweru\AppData\Local\Temp\ipykernel_61284\3185563332.py:4: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `WeightedLossTrainer.__init__`. Use `processing_class` instead.
  super().__init__(*args, **kwargs)

Training time for bert: 115.49 seconds
Best checkpoint for bert: D:/huggingface_cache/classification_models/bert\checkpoint-1264

Prediction time for bert: 2.07 seconds

Classification Report for bert:
              precision    recall  f1-score   support

           0     0.9216    0.8991    0.9102       327
           1     0.9651    0.9733    0.9692       937

    accuracy                         0.9541      1264
   macro avg     0.9434    0.9362    0.9397      1264
weighted avg     0.9538    0.9541    0.9539      1264

{'model': 'bert', 'max_length': 128, 'train_time_sec': 115.4943515625, 'pred_time_sec': 2.065423095703125, 'best_checkpoint': 'D:/huggingface_cache/classification_models/bert\\checkpoint-1264', 'accuracy': 0.9541139240506329, 'f1': 0.9539273259389034, 'precision': 0.9538389286643325, 'recall': 0.9541139240506329}

--- Training bert with max_length=256 ---

===== Training bert =====

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Map:   0%|          | 0/5052 [00:00<?, ? examples/s]

Map:   0%|          | 0/1264 [00:00<?, ? examples/s]

C:\Users\ctngweru\AppData\Local\Temp\ipykernel_61284\3185563332.py:4: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `WeightedLossTrainer.__init__`. Use `processing_class` instead.
  super().__init__(*args, **kwargs)

Training time for bert: 207.31 seconds
Best checkpoint for bert: D:/huggingface_cache/classification_models/bert\checkpoint-1264

Prediction time for bert: 3.71 seconds

Classification Report for bert:
              precision    recall  f1-score   support

           0     0.9404    0.8685    0.9030       327
           1     0.9553    0.9808    0.9679       937

    accuracy                         0.9517      1264
   macro avg     0.9478    0.9246    0.9354      1264
weighted avg     0.9514    0.9517    0.9511      1264

{'model': 'bert', 'max_length': 256, 'train_time_sec': 207.312140625, 'pred_time_sec': 3.71302294921875, 'best_checkpoint': 'D:/huggingface_cache/classification_models/bert\\checkpoint-1264', 'accuracy': 0.9517405063291139, 'f1': 0.9510991182485115, 'precision': 0.9514457257850459, 'recall': 0.9517405063291139}

--- Training bert with max_length=512 ---

===== Training bert =====

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Map:   0%|          | 0/5052 [00:00<?, ? examples/s]

Map:   0%|          | 0/1264 [00:00<?, ? examples/s]

C:\Users\ctngweru\AppData\Local\Temp\ipykernel_61284\3185563332.py:4: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `WeightedLossTrainer.__init__`. Use `processing_class` instead.
  super().__init__(*args, **kwargs)

Training time for bert: 292.03 seconds
Best checkpoint for bert: D:/huggingface_cache/classification_models/bert\checkpoint-1264

Prediction time for bert: 6.88 seconds

Classification Report for bert:
              precision    recall  f1-score   support

           0     0.9549    0.8410    0.8943       327
           1     0.9467    0.9861    0.9660       937

    accuracy                         0.9486      1264
   macro avg     0.9508    0.9136    0.9302      1264
weighted avg     0.9488    0.9486    0.9475      1264

{'model': 'bert', 'max_length': 512, 'train_time_sec': 292.02684375, 'pred_time_sec': 6.87504638671875, 'best_checkpoint': 'D:/huggingface_cache/classification_models/bert\\checkpoint-1264', 'accuracy': 0.9485759493670886, 'f1': 0.9474696172997448, 'precision': 0.9488270982482534, 'recall': 0.9485759493670886}
Skipping xlnet with max_length=128 (already in CSV).
Skipping xlnet with max_length=256 (already in CSV).
Skipping xlnet with max_length=512 (already in CSV).
Skipping roberta with max_length=128 (already in CSV).
Skipping roberta with max_length=256 (already in CSV).
Skipping roberta with max_length=512 (already in CSV).
Skipping deberta-v3-base with max_length=128 (already in CSV).
Skipping deberta-v3-base with max_length=256 (already in CSV).
Skipping deberta-v3-base with max_length=512 (already in CSV).
Skipping xlm-roberta-base with max_length=128 (already in CSV).
Skipping xlm-roberta-base with max_length=256 (already in CSV).
Skipping xlm-roberta-base with max_length=512 (already in CSV).
Skipping bert-large-uncased with max_length=128 (already in CSV).
Skipping bert-large-uncased with max_length=256 (already in CSV).
Skipping bert-large-uncased with max_length=512 (already in CSV).
Skipping roberta-large with max_length=128 (already in CSV).
Skipping roberta-large with max_length=256 (already in CSV).
Skipping roberta-large with max_length=512 (already in CSV).
Skipping electra-large with max_length=128 (already in CSV).
Skipping electra-large with max_length=256 (already in CSV).
Skipping electra-large with max_length=512 (already in CSV).
Skipping xlm-roberta-large with max_length=128 (already in CSV).
Skipping xlm-roberta-large with max_length=256 (already in CSV).
Skipping xlm-roberta-large with max_length=512 (already in CSV).
Skipping deberta-large with max_length=128 (already in CSV).
Skipping deberta-large with max_length=256 (already in CSV).
Skipping deberta-large with max_length=512 (already in CSV).