#### Imports

In [23]:
import pandas as pd
import torch
import numpy as np
import os
from sklearn.model_selection import train_test_split
from sklearn.utils.class_weight import compute_class_weight
from datasets import Dataset
from huggingface_hub import login
import logging
from transformers import (
    TrainingArguments,
    Trainer,
    AutoModelForSequenceClassification,
    # tokenizers
    AutoTokenizer,
    DebertaV2Tokenizer,
    DistilBertTokenizer,
    BertTokenizer,
    RobertaTokenizer,
    ElectraTokenizer,
    AlbertTokenizer,
    XLNetTokenizer,
    MobileBertTokenizer,
    # models
    DebertaV2ForSequenceClassification,
    DistilBertForSequenceClassification,
    BertForSequenceClassification,
    RobertaForSequenceClassification,
    ElectraForSequenceClassification,
    AlbertForSequenceClassification,
    XLNetForSequenceClassification,
    MobileBertForSequenceClassification,
)
from torch.nn import CrossEntropyLoss
# evaluation metrics
from sklearn.metrics import accuracy_score, precision_recall_fscore_support, classification_report
from collections import Counter

import transformers
print(transformers.__version__)
print(transformers.TrainingArguments)

# Cuda
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

4.53.2
<class 'transformers.training_args.TrainingArguments'>

In [24]:
logging.basicConfig(filename='classification_nvidia.log', level=logging.INFO)
logging.info(f"Running on device: {device}")

In [25]:
# setting huggingface token
login(token=os.getenv("HUGGINGFACE_TOKEN"))

os.environ["HF_HOME"] = "huggingface_cache" 
os.environ["TRANSFORMERS_CACHE"] = "huggingface_cache"
os.environ["HUGGINGFACE_HUB_CACHE"] = "huggingface_cache"

print("HF_HOME:", os.getenv("HF_HOME"))
print("TRANSFORMERS_CACHE:", os.getenv("TRANSFORMERS_CACHE"))
print("HUGGINGFACE_HUB_CACHE:", os.getenv("HUGGINGFACE_HUB_CACHE"))

logging.info(f"HF_HOME: {os.getenv('HF_HOME')}")
logging.info(f"TRANSFORMERS_CACHE: {os.getenv('TRANSFORMERS_CACHE')}")
logging.info(f"HUGGINGFACE_HUB_CACHE: {os.getenv('HUGGINGFACE_HUB_CACHE')}")

transformers.utils.hub.TRANSFORMERS_CACHE = "huggingface_cache"

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

HF_HOME: huggingface_cache
TRANSFORMERS_CACHE: huggingface_cache
HUGGINGFACE_HUB_CACHE: huggingface_cache

### LOADING SQLITE DB WITH RECORDS

In [26]:
import sqlite3
import json
import pandas as pd

DB_FILE = "chunks.db"
OUTPUT_FILE = "exported_chunks.jsonl"

# Connect to the database
conn = sqlite3.connect(DB_FILE)
cur = conn.cursor()

# Query all data from chunks table
cur.execute("SELECT text, label FROM chunks")
rows = cur.fetchall()

# Write to JSONL
with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
    for text, label in rows:
        obj = {"text": text}
        if label is not None:
            obj["label"] = label
        f.write(json.dumps(obj) + "\n")

conn.close()

print("Data exported to JSONL file.")

Data exported to JSONL file.

In [27]:
# Load the labeled chunks
with open("exported_chunks.jsonl", "r", encoding="utf-8") as f:
    labeled_chunks = [json.loads(line) for line in f]

data = pd.DataFrame(labeled_chunks)
labeled_count = data['label'].value_counts().to_dict()

# Get the first 9000 rows
data = data.head(9000)

# Remove rows with label == 11
data = data[data['label'] != 11]

# Print labeled count after removing label 11
labeled_count = data['label'].value_counts().to_dict()
print(f"Labeled chunks after removing label 11: {labeled_count}")

# Remove rows where label == 1 and text length < 100
data = data[~((data['label'] == 1) & (data['text'].str.len() < 100))]

# Print final labeled count
labeled_count = data['label'].value_counts().to_dict()
print(f"Final labeled chunks: {labeled_count}")

Labeled chunks after removing label 11: {1: 8199, 0: 800}
Final labeled chunks: {1: 5384, 0: 800}

##### Spliting data

In [28]:
# Loading the data
data['label'] = data['label'].astype(int)

# Train-Test Split using stratified sampling
train_df, test_df = train_test_split(data, test_size=0.2, stratify=data['label'], random_state=42)

# since there is a class imbalance, we will compute class weights
# to handle this in the loss function
labels = train_df["label"].values
# Compute class weights
classes = np.unique(labels)
weights = compute_class_weight(class_weight="balanced",
                            classes=classes,
                            y=labels)
class_weights = torch.tensor(weights, dtype=torch.float, device=device)
print("Class weights:", class_weights)

# Convert ing the DataFrames to Hugging Face Datasets
train_dataset = Dataset.from_pandas(train_df.reset_index(drop=True))
test_dataset = Dataset.from_pandas(test_df.reset_index(drop=True))

Class weights: tensor([3.8648, 0.5743], device='cuda:0')

In [29]:
# ---- Tuning parameters ----
CONFIG = {
    # tuned number of epochs
    "epochs": {
        "xs": 4,
        "s": 3,
        "m": 3,
        "l": 2,
        "xl": 2,
        "xxl": 2
    },
    # batch sizes tuned by model size/type
    "batch_size": {
        "xs": 32,
        "s": 16,
        "m": 8,
        "l": 4,
        "xl": 2,
        "xxl": 1
    },
    "max_length": [128, 256, 512],  # Max length of input sequences
    # learning rates tuned by model size/type
    "learning_rate": {
        "xs": 5e-5,
        "s": 5e-5,
        "m": 3e-5,
        "l": 3e-5,
        "xl": 2e-5,
        "xxl": 1e-5
    },
    "weight_decay": 0.01,  # Weight decay for regularization
    "output_dir": "huggingface_cache/classification_models"
}

# ---- Model configurations ----
# Ordered roughly by parameter count (small -> xxl). Each model has a 'type' key.
MODEL_CONFIGS = {
    # ---- XS (very small, <= ~20M) ----
    "albert-base-v2": {
        "type": "xs",
        "tokenizer_class": AlbertTokenizer,
        "pretrained_model_name": "albert-base-v2",  # ~11M
        "model_class": AlbertForSequenceClassification
    },
    "albert-base-v1": {
        "type": "xs",
        "tokenizer_class": AlbertTokenizer,
        "pretrained_model_name": "albert-base-v1",  # ~12M
        "model_class": AlbertForSequenceClassification
    },
    "electra-small": {
        "type": "xs",
        "tokenizer_class": ElectraTokenizer,
        "pretrained_model_name": "google/electra-small-discriminator",  # ~14M
        "model_class": ElectraForSequenceClassification
    },
    "albert-large-v2": {
        "type": "xs",
        "tokenizer_class": AlbertTokenizer,
        "pretrained_model_name": "albert-large-v2",  # ~18M
        "model_class": AlbertForSequenceClassification
    },

    # ---- S (small, ~20M-70M) ----
    "mobilebert": {
        "type": "s",
        "tokenizer_class": AutoTokenizer,
        "pretrained_model_name": "google/mobilebert-uncased",  # ~25M
        "model_class": MobileBertForSequenceClassification
    },
    "deberta-v3-small": {
        "type": "s",
        "tokenizer_class": DebertaV2Tokenizer,
        "pretrained_model_name": "microsoft/deberta-v3-small",  # ~55M
        "model_class": DebertaV2ForSequenceClassification
    },
    "albert-xlarge-v2": {
        "type": "s",
        "tokenizer_class": AlbertTokenizer,
        "pretrained_model_name": "albert-xlarge-v2",  # ~60M
        "model_class": AlbertForSequenceClassification
    },
    "distilbert": {
        "type": "s",
        "tokenizer_class": DistilBertTokenizer,
        "pretrained_model_name": "distilbert-base-uncased",  # ~66M
        "model_class": DistilBertForSequenceClassification
    },

    # ---- M (medium, ~70M-200M) ----
    "bert": {
        "type": "m",
        "tokenizer_class": BertTokenizer,
        "pretrained_model_name": "bert-base-uncased",  # ~110M
        "model_class": BertForSequenceClassification
    },
    "xlnet": {
        "type": "m",
        "tokenizer_class": XLNetTokenizer,
        "pretrained_model_name": "xlnet-base-cased",  # ~110M
        "model_class": XLNetForSequenceClassification
    },
    "electra-base-generator": {
        "type": "m",
        "tokenizer_class": ElectraTokenizer,
        "pretrained_model_name": "google/electra-base-generator",  # ~110M
        "model_class": ElectraForSequenceClassification
    },
    "roberta": {
        "type": "m",
        "tokenizer_class": RobertaTokenizer,
        "pretrained_model_name": "roberta-base",  # ~125M
        "model_class": RobertaForSequenceClassification
    },
     # ---- Mid-range / other configs kept (type inferred) ----
    "deberta-v3-base": {
        "type": "m",
        "tokenizer_class": AutoTokenizer,
        "pretrained_model_name": "microsoft/deberta-v3-base", # ~140M
        "model_class": AutoModelForSequenceClassification
    },

    # ---- L (large, ~200M-400M) ----
    "xlm-roberta-base": {
        "type": "l",
        "tokenizer_class": AutoTokenizer,
        "pretrained_model_name": "xlm-roberta-base",  # ~270M
        "model_class": AutoModelForSequenceClassification
    },
    "bert-large-uncased": {
        "type": "l",
        "tokenizer_class": BertTokenizer,
        "pretrained_model_name": "bert-large-uncased",  # ~340M
        "model_class": BertForSequenceClassification
    },
    "roberta-large": {
        "type": "l",
        "tokenizer_class": RobertaTokenizer,
        "pretrained_model_name": "roberta-large",  # ~355M
        "model_class": RobertaForSequenceClassification
    },
    "electra-large": {
        "type": "l",
        "tokenizer_class": ElectraTokenizer,
        "pretrained_model_name": "google/electra-large-discriminator",  # ~335M
        "model_class": ElectraForSequenceClassification
    },
    # ---- XL (extra large, ~400M-800M) ----
    "xlm-roberta-large": {
        "type": "xl",
        "tokenizer_class": AutoTokenizer,
        "pretrained_model_name": "xlm-roberta-large",  # ~550M
        "model_class": AutoModelForSequenceClassification
    },
    # ---- XXL (very large, > ~800M) ----
    "deberta-large": {
        "type": "xxl",
        "tokenizer_class": AutoTokenizer,
        "pretrained_model_name": "microsoft/deberta-large",  # very large (~>800M depending on variant)
        "model_class": AutoModelForSequenceClassification
    },
    "deberta-v3-large": {
        "type": "xxl",
        "tokenizer_class": AutoTokenizer,
        "pretrained_model_name": "microsoft/deberta-v3-large",  # very large (~>1B)
        "model_class": AutoModelForSequenceClassification
    },
    "deberta-xlarge": {
        "type": "xxl",
        "tokenizer_class": AutoTokenizer,
        "pretrained_model_name": "microsoft/deberta-xlarge", # very large (~>800M)
        "model_class": AutoModelForSequenceClassification
    }
}

In [30]:

# ---- Metric function ----
def compute_metrics(pred):
    labels = pred.label_ids
    preds = pred.predictions.argmax(-1)
    precision, recall, f1, _ = precision_recall_fscore_support(labels, preds, average='weighted')
    acc = accuracy_score(labels, preds)
    return {'accuracy': acc, 'f1': f1, 'precision': precision, 'recall': recall}

In [31]:
# ---- Weighted Trainer ----
class WeightedLossTrainer(Trainer):
    def __init__(self, class_weights=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.class_weights = class_weights

    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        labels = inputs.get("labels")
        outputs = model(**inputs)
        logits = outputs.get("logits")
        loss_fct = CrossEntropyLoss(weight=self.class_weights)
        loss = loss_fct(logits, labels)
        return (loss, outputs) if return_outputs else loss

In [32]:

# ---- Function to train and evaluate ----
def train_and_evaluate(model_name, train_dataset, test_dataset, data, max_length):
    print(f"\n===== Training {model_name} =====")

    # Model + tokenizer
    cfg = MODEL_CONFIGS[model_name]
    tokenizer = cfg["tokenizer_class"].from_pretrained(cfg["pretrained_model_name"])
    model = cfg["model_class"].from_pretrained(
        cfg["pretrained_model_name"],
        num_labels=len(data['label'].unique())
    )

    # Tokenization
    def tokenize_fn(batch):
        return tokenizer(batch["text"], truncation=True, padding="max_length", max_length=max_length)

    train_enc = train_dataset.map(tokenize_fn, batched=True)
    test_enc = test_dataset.map(tokenize_fn, batched=True)
    train_enc = train_enc.rename_column("label", "labels")
    test_enc = test_enc.rename_column("label", "labels")
    train_enc.set_format(type="torch", columns=["input_ids", "attention_mask", "labels"])
    test_enc.set_format(type="torch", columns=["input_ids", "attention_mask", "labels"])

    # Training args
    training_args = TrainingArguments(
        output_dir=f"{CONFIG['output_dir']}/{model_name}",
        eval_strategy="epoch",
        save_strategy="epoch",
        learning_rate= CONFIG["learning_rate"][cfg["type"]],
        per_device_train_batch_size=CONFIG["batch_size"][cfg["type"]],
        per_device_eval_batch_size=CONFIG["batch_size"][cfg["type"]],
        num_train_epochs=CONFIG["epochs"][cfg["type"]],
        weight_decay=CONFIG["weight_decay"],
        logging_dir=f"./logs_{model_name}",
        report_to="none",
        load_best_model_at_end=True,
        metric_for_best_model="f1",
        seed=42
    )

    # Trainer
    trainer = WeightedLossTrainer(
        model=model,
        args=training_args,
        train_dataset=train_enc,
        eval_dataset=test_enc,
        compute_metrics=compute_metrics,
        tokenizer=tokenizer,
        class_weights=class_weights
    )

    # Train + evaluate
    # time to train
    t_train_start = torch.cuda.Event(enable_timing=True)
    t_train_end = torch.cuda.Event(enable_timing=True)
    t_train_start.record()
    trainer.train()
    t_train_end.record()
    torch.cuda.synchronize()
    t_train_time = t_train_start.elapsed_time(t_train_end) / 1000  # convert to seconds
    print(f"Training time for {model_name}: {t_train_time:.2f} seconds")

    # Predictions
    t_pred_start = torch.cuda.Event(enable_timing=True)
    t_pred_end = torch.cuda.Event(enable_timing=True)
    t_pred_start.record()
    preds = trainer.predict(test_enc)
    t_pred_end.record()
    torch.cuda.synchronize()
    t_pred_time = t_pred_start.elapsed_time(t_pred_end) / 1000  # convert to seconds
    print(f"Prediction time for {model_name}: {t_pred_time:.2f} seconds")
    y_true = preds.label_ids
    y_pred = np.argmax(preds.predictions, axis=1)

    print(f"\nClassification Report for {model_name}:")
    print(classification_report(y_true, y_pred, digits=4))

    performance = {
        "model": model_name,
        "max_length": max_length,
        "train_time_sec": t_train_time,
        "pred_time_sec": t_pred_time,
        "accuracy": accuracy_score(y_true, y_pred),
        "f1": precision_recall_fscore_support(y_true, y_pred, average='weighted')[2],
        "precision": precision_recall_fscore_support(y_true, y_pred, average='weighted')[0],
        "recall": precision_recall_fscore_support(y_true, y_pred, average='weighted')[1],
    }
    return performance

In [33]:
for model_name in MODEL_CONFIGS.keys():
    for max_len in CONFIG["max_length"]:
        # skip if this (model, max_len) already exists in CSV
        if os.path.exists("model_performance_nvidia.csv") and f"{model_name},{max_len}," in open("model_performance_nvidia.csv").read():
            print(f"Skipping {model_name} with max_length={max_len} (already in CSV).")
            continue

        print(f"\n--- Training {model_name} with max_length={max_len} ---")
        performance = train_and_evaluate(model_name, train_dataset, test_dataset, data, max_len)
        print(performance)
        # save performance to a csv file
        with open("model_performance_nvidia.csv", "a") as f:
            #headers if file is empty
            if os.stat("model_performance_nvidia.csv").st_size == 0:
                f.write("model,max_length,train_time_sec,pred_time_sec,accuracy,f1,precision,recall\n")
            f.write(",".join([str(performance[k]) for k in performance]) + "\n")

Skipping albert-base-v2 with max_length=128 (already in CSV).
Skipping albert-base-v2 with max_length=256 (already in CSV).
Skipping albert-base-v2 with max_length=512 (already in CSV).
Skipping albert-base-v1 with max_length=128 (already in CSV).
Skipping albert-base-v1 with max_length=256 (already in CSV).
Skipping albert-base-v1 with max_length=512 (already in CSV).
Skipping electra-small with max_length=128 (already in CSV).
Skipping electra-small with max_length=256 (already in CSV).
Skipping electra-small with max_length=512 (already in CSV).
Skipping albert-large-v2 with max_length=128 (already in CSV).
Skipping albert-large-v2 with max_length=256 (already in CSV).
Skipping albert-large-v2 with max_length=512 (already in CSV).
Skipping mobilebert with max_length=128 (already in CSV).
Skipping mobilebert with max_length=256 (already in CSV).
Skipping mobilebert with max_length=512 (already in CSV).
Skipping deberta-v3-small with max_length=128 (already in CSV).
Skipping deberta-v3-small with max_length=256 (already in CSV).
Skipping deberta-v3-small with max_length=512 (already in CSV).
Skipping albert-xlarge-v2 with max_length=128 (already in CSV).
Skipping albert-xlarge-v2 with max_length=256 (already in CSV).
Skipping albert-xlarge-v2 with max_length=512 (already in CSV).
Skipping distilbert with max_length=128 (already in CSV).
Skipping distilbert with max_length=256 (already in CSV).
Skipping distilbert with max_length=512 (already in CSV).
Skipping bert with max_length=128 (already in CSV).
Skipping bert with max_length=256 (already in CSV).
Skipping bert with max_length=512 (already in CSV).
Skipping xlnet with max_length=128 (already in CSV).
Skipping xlnet with max_length=256 (already in CSV).
Skipping xlnet with max_length=512 (already in CSV).
Skipping electra-base-generator with max_length=128 (already in CSV).
Skipping electra-base-generator with max_length=256 (already in CSV).
Skipping electra-base-generator with max_length=512 (already in CSV).
Skipping roberta with max_length=128 (already in CSV).
Skipping roberta with max_length=256 (already in CSV).
Skipping roberta with max_length=512 (already in CSV).
Skipping deberta-v3-base with max_length=128 (already in CSV).
Skipping deberta-v3-base with max_length=256 (already in CSV).
Skipping deberta-v3-base with max_length=512 (already in CSV).
Skipping xlm-roberta-base with max_length=128 (already in CSV).
Skipping xlm-roberta-base with max_length=256 (already in CSV).
Skipping xlm-roberta-base with max_length=512 (already in CSV).
Skipping bert-large-uncased with max_length=128 (already in CSV).
Skipping bert-large-uncased with max_length=256 (already in CSV).
Skipping bert-large-uncased with max_length=512 (already in CSV).
Skipping roberta-large with max_length=128 (already in CSV).
Skipping roberta-large with max_length=256 (already in CSV).
Skipping roberta-large with max_length=512 (already in CSV).
Skipping electra-large with max_length=128 (already in CSV).
Skipping electra-large with max_length=256 (already in CSV).
Skipping electra-large with max_length=512 (already in CSV).

--- Training xlm-roberta-large with max_length=128 ---

===== Training xlm-roberta-large =====

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.10M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/2.24G [00:00<?, ?B/s]

Some weights of XLMRobertaForSequenceClassification were not initialized from the model checkpoint at xlm-roberta-large and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Map:   0%|          | 0/4947 [00:00<?, ? examples/s]

Map:   0%|          | 0/1237 [00:00<?, ? examples/s]

/tmp/ipykernel_2580169/3185563332.py:4: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `WeightedLossTrainer.__init__`. Use `processing_class` instead.
  super().__init__(*args, **kwargs)

/home/spark/anaconda3/envs/lmforge/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/spark/anaconda3/envs/lmforge/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Training time for xlm-roberta-large: 1624.69 seconds

/home/spark/anaconda3/envs/lmforge/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/spark/anaconda3/envs/lmforge/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/spark/anaconda3/envs/lmforge/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/spark/anaconda3/envs/lmforge/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/spark/anaconda3/envs/lmforge/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/spark/anaconda3/envs/lmforge/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/spark/anaconda3/envs/lmforge/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Prediction time for xlm-roberta-large: 15.19 seconds

Classification Report for xlm-roberta-large:
              precision    recall  f1-score   support

           0     0.0000    0.0000    0.0000       160
           1     0.8707    1.0000    0.9309      1077

    accuracy                         0.8707      1237
   macro avg     0.4353    0.5000    0.4654      1237
weighted avg     0.7580    0.8707    0.8105      1237

{'model': 'xlm-roberta-large', 'max_length': 128, 'train_time_sec': 1624.692875, 'pred_time_sec': 15.191505859375, 'accuracy': 0.8706548100242523, 'f1': 0.8104539588557645, 'precision': 0.7580397982183668, 'recall': 0.8706548100242523}

--- Training xlm-roberta-large with max_length=256 ---

===== Training xlm-roberta-large =====

Some weights of XLMRobertaForSequenceClassification were not initialized from the model checkpoint at xlm-roberta-large and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Map:   0%|          | 0/4947 [00:00<?, ? examples/s]

Map:   0%|          | 0/1237 [00:00<?, ? examples/s]

/tmp/ipykernel_2580169/3185563332.py:4: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `WeightedLossTrainer.__init__`. Use `processing_class` instead.
  super().__init__(*args, **kwargs)

Training time for xlm-roberta-large: 1774.17 seconds

Prediction time for xlm-roberta-large: 21.24 seconds

Classification Report for xlm-roberta-large:
              precision    recall  f1-score   support

           0     0.9786    0.8562    0.9133       160
           1     0.9790    0.9972    0.9880      1077

    accuracy                         0.9790      1237
   macro avg     0.9788    0.9267    0.9507      1237
weighted avg     0.9790    0.9790    0.9784      1237

{'model': 'xlm-roberta-large', 'max_length': 256, 'train_time_sec': 1774.165125, 'pred_time_sec': 21.2355703125, 'accuracy': 0.978981406628941, 'f1': 0.9783774685121461, 'precision': 0.9789739320973547, 'recall': 0.978981406628941}

--- Training xlm-roberta-large with max_length=512 ---

===== Training xlm-roberta-large =====

Some weights of XLMRobertaForSequenceClassification were not initialized from the model checkpoint at xlm-roberta-large and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Map:   0%|          | 0/4947 [00:00<?, ? examples/s]

Map:   0%|          | 0/1237 [00:00<?, ? examples/s]

/tmp/ipykernel_2580169/3185563332.py:4: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `WeightedLossTrainer.__init__`. Use `processing_class` instead.
  super().__init__(*args, **kwargs)

Training time for xlm-roberta-large: 2267.89 seconds

Prediction time for xlm-roberta-large: 41.72 seconds

Classification Report for xlm-roberta-large:
              precision    recall  f1-score   support

           0     0.9185    0.7750    0.8407       160
           1     0.9673    0.9898    0.9784      1077

    accuracy                         0.9620      1237
   macro avg     0.9429    0.8824    0.9096      1237
weighted avg     0.9610    0.9620    0.9606      1237

{'model': 'xlm-roberta-large', 'max_length': 512, 'train_time_sec': 2267.8905, 'pred_time_sec': 41.723484375, 'accuracy': 0.9620048504446241, 'f1': 0.9606128485590927, 'precision': 0.9610183184136326, 'recall': 0.9620048504446241}

--- Training deberta-large with max_length=128 ---

===== Training deberta-large =====

tokenizer_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/475 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

pytorch_model.bin:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

Some weights of DebertaForSequenceClassification were not initialized from the model checkpoint at microsoft/deberta-large and are newly initialized: ['classifier.bias', 'classifier.weight', 'pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Map:   0%|          | 0/4947 [00:00<?, ? examples/s]

Map:   0%|          | 0/1237 [00:00<?, ? examples/s]

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

/tmp/ipykernel_2580169/3185563332.py:4: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `WeightedLossTrainer.__init__`. Use `processing_class` instead.
  super().__init__(*args, **kwargs)

Training time for deberta-large: 2589.74 seconds

Prediction time for deberta-large: 37.11 seconds

Classification Report for deberta-large:
              precision    recall  f1-score   support

           0     0.9655    0.8750    0.9180       160
           1     0.9817    0.9954    0.9885      1077

    accuracy                         0.9798      1237
   macro avg     0.9736    0.9352    0.9533      1237
weighted avg     0.9796    0.9798    0.9794      1237

{'model': 'deberta-large', 'max_length': 128, 'train_time_sec': 2589.74075, 'pred_time_sec': 37.11095703125, 'accuracy': 0.9797898140662894, 'f1': 0.9793627253582601, 'precision': 0.9795937622436659, 'recall': 0.9797898140662894}

--- Training deberta-large with max_length=256 ---

===== Training deberta-large =====

Some weights of DebertaForSequenceClassification were not initialized from the model checkpoint at microsoft/deberta-large and are newly initialized: ['classifier.bias', 'classifier.weight', 'pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Map:   0%|          | 0/4947 [00:00<?, ? examples/s]

Map:   0%|          | 0/1237 [00:00<?, ? examples/s]

/tmp/ipykernel_2580169/3185563332.py:4: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `WeightedLossTrainer.__init__`. Use `processing_class` instead.
  super().__init__(*args, **kwargs)

Training time for deberta-large: 2939.95 seconds

Prediction time for deberta-large: 49.74 seconds

Classification Report for deberta-large:
              precision    recall  f1-score   support

           0     0.9793    0.8875    0.9311       160
           1     0.9835    0.9972    0.9903      1077

    accuracy                         0.9830      1237
   macro avg     0.9814    0.9424    0.9607      1237
weighted avg     0.9830    0.9830    0.9827      1237

{'model': 'deberta-large', 'max_length': 256, 'train_time_sec': 2939.949, 'pred_time_sec': 49.74116796875, 'accuracy': 0.9830234438156831, 'f1': 0.9826646893009385, 'precision': 0.9829724397087037, 'recall': 0.9830234438156831}

--- Training deberta-large with max_length=512 ---

===== Training deberta-large =====

Some weights of DebertaForSequenceClassification were not initialized from the model checkpoint at microsoft/deberta-large and are newly initialized: ['classifier.bias', 'classifier.weight', 'pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Map:   0%|          | 0/4947 [00:00<?, ? examples/s]

Map:   0%|          | 0/1237 [00:00<?, ? examples/s]

/tmp/ipykernel_2580169/3185563332.py:4: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `WeightedLossTrainer.__init__`. Use `processing_class` instead.
  super().__init__(*args, **kwargs)

Training time for deberta-large: 4522.50 seconds

Prediction time for deberta-large: 111.34 seconds

Classification Report for deberta-large:
              precision    recall  f1-score   support

           0     0.9660    0.8875    0.9251       160
           1     0.9835    0.9954    0.9894      1077

    accuracy                         0.9814      1237
   macro avg     0.9747    0.9414    0.9572      1237
weighted avg     0.9812    0.9814    0.9811      1237

{'model': 'deberta-large', 'max_length': 512, 'train_time_sec': 4522.5005, 'pred_time_sec': 111.3387265625, 'accuracy': 0.9814066289409863, 'f1': 0.9810687297511795, 'precision': 0.98122271788871, 'recall': 0.9814066289409863}

--- Training deberta-v3-large with max_length=128 ---

===== Training deberta-v3-large =====

tokenizer_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/580 [00:00<?, ?B/s]

spm.model:   0%|          | 0.00/2.46M [00:00<?, ?B/s]

/home/spark/anaconda3/envs/lmforge/lib/python3.10/site-packages/transformers/convert_slow_tokenizer.py:564: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(

pytorch_model.bin:   0%|          | 0.00/874M [00:00<?, ?B/s]

Some weights of DebertaV2ForSequenceClassification were not initialized from the model checkpoint at microsoft/deberta-v3-large and are newly initialized: ['classifier.bias', 'classifier.weight', 'pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Map:   0%|          | 0/4947 [00:00<?, ? examples/s]

model.safetensors:   0%|          | 0.00/874M [00:00<?, ?B/s]

Map:   0%|          | 0/1237 [00:00<?, ? examples/s]

/tmp/ipykernel_2580169/3185563332.py:4: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `WeightedLossTrainer.__init__`. Use `processing_class` instead.
  super().__init__(*args, **kwargs)

Training time for deberta-v3-large: 2771.03 seconds

Prediction time for deberta-v3-large: 40.74 seconds

Classification Report for deberta-v3-large:
              precision    recall  f1-score   support

           0     0.9456    0.8688    0.9055       160
           1     0.9807    0.9926    0.9866      1077

    accuracy                         0.9766      1237
   macro avg     0.9632    0.9307    0.9461      1237
weighted avg     0.9762    0.9766    0.9761      1237

{'model': 'deberta-v3-large', 'max_length': 128, 'train_time_sec': 2771.03225, 'pred_time_sec': 40.74128515625, 'accuracy': 0.9765561843168957, 'f1': 0.9761301375123569, 'precision': 0.9761867224918342, 'recall': 0.9765561843168957}

--- Training deberta-v3-large with max_length=256 ---

===== Training deberta-v3-large =====

/home/spark/anaconda3/envs/lmforge/lib/python3.10/site-packages/transformers/convert_slow_tokenizer.py:564: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
Some weights of DebertaV2ForSequenceClassification were not initialized from the model checkpoint at microsoft/deberta-v3-large and are newly initialized: ['classifier.bias', 'classifier.weight', 'pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Map:   0%|          | 0/4947 [00:00<?, ? examples/s]

Map:   0%|          | 0/1237 [00:00<?, ? examples/s]

/tmp/ipykernel_2580169/3185563332.py:4: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `WeightedLossTrainer.__init__`. Use `processing_class` instead.
  super().__init__(*args, **kwargs)

Training time for deberta-v3-large: 3081.35 seconds

Prediction time for deberta-v3-large: 51.81 seconds

Classification Report for deberta-v3-large:
              precision    recall  f1-score   support

           0     0.9793    0.8875    0.9311       160
           1     0.9835    0.9972    0.9903      1077

    accuracy                         0.9830      1237
   macro avg     0.9814    0.9424    0.9607      1237
weighted avg     0.9830    0.9830    0.9827      1237

{'model': 'deberta-v3-large', 'max_length': 256, 'train_time_sec': 3081.34675, 'pred_time_sec': 51.81464453125, 'accuracy': 0.9830234438156831, 'f1': 0.9826646893009385, 'precision': 0.9829724397087037, 'recall': 0.9830234438156831}

--- Training deberta-v3-large with max_length=512 ---

===== Training deberta-v3-large =====

/home/spark/anaconda3/envs/lmforge/lib/python3.10/site-packages/transformers/convert_slow_tokenizer.py:564: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
Some weights of DebertaV2ForSequenceClassification were not initialized from the model checkpoint at microsoft/deberta-v3-large and are newly initialized: ['classifier.bias', 'classifier.weight', 'pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Map:   0%|          | 0/4947 [00:00<?, ? examples/s]

Map:   0%|          | 0/1237 [00:00<?, ? examples/s]

/tmp/ipykernel_2580169/3185563332.py:4: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `WeightedLossTrainer.__init__`. Use `processing_class` instead.
  super().__init__(*args, **kwargs)

Training time for deberta-v3-large: 4186.88 seconds

Prediction time for deberta-v3-large: 103.45 seconds

Classification Report for deberta-v3-large:
              precision    recall  f1-score   support

           0     0.9530    0.8875    0.9191       160
           1     0.9835    0.9935    0.9885      1077

    accuracy                         0.9798      1237
   macro avg     0.9682    0.9405    0.9538      1237
weighted avg     0.9795    0.9798    0.9795      1237

{'model': 'deberta-v3-large', 'max_length': 512, 'train_time_sec': 4186.88125, 'pred_time_sec': 103.4475, 'accuracy': 0.9797898140662894, 'f1': 0.9794814281114305, 'precision': 0.9795191647296909, 'recall': 0.9797898140662894}

--- Training deberta-xlarge with max_length=128 ---

===== Training deberta-xlarge =====

tokenizer_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/475 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

pytorch_model.bin:   0%|          | 0.00/1.52G [00:00<?, ?B/s]

Some weights of DebertaForSequenceClassification were not initialized from the model checkpoint at microsoft/deberta-xlarge and are newly initialized: ['classifier.bias', 'classifier.weight', 'pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Map:   0%|          | 0/4947 [00:00<?, ? examples/s]

model.safetensors:   0%|          | 0.00/1.52G [00:00<?, ?B/s]

Map:   0%|          | 0/1237 [00:00<?, ? examples/s]

/tmp/ipykernel_2580169/3185563332.py:4: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `WeightedLossTrainer.__init__`. Use `processing_class` instead.
  super().__init__(*args, **kwargs)

Training time for deberta-xlarge: 4897.87 seconds

Prediction time for deberta-xlarge: 68.05 seconds

Classification Report for deberta-xlarge:
              precision    recall  f1-score   support

           0     0.9720    0.8688    0.9175       160
           1     0.9808    0.9963    0.9885      1077

    accuracy                         0.9798      1237
   macro avg     0.9764    0.9325    0.9530      1237
weighted avg     0.9797    0.9798    0.9793      1237

{'model': 'deberta-xlarge', 'max_length': 128, 'train_time_sec': 4897.871, 'pred_time_sec': 68.0470078125, 'accuracy': 0.9797898140662894, 'f1': 0.9793019895139387, 'precision': 0.979669200433153, 'recall': 0.9797898140662894}

--- Training deberta-xlarge with max_length=256 ---

===== Training deberta-xlarge =====

Some weights of DebertaForSequenceClassification were not initialized from the model checkpoint at microsoft/deberta-xlarge and are newly initialized: ['classifier.bias', 'classifier.weight', 'pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Map:   0%|          | 0/4947 [00:00<?, ? examples/s]

Map:   0%|          | 0/1237 [00:00<?, ? examples/s]

/tmp/ipykernel_2580169/3185563332.py:4: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `WeightedLossTrainer.__init__`. Use `processing_class` instead.
  super().__init__(*args, **kwargs)

/home/spark/anaconda3/envs/lmforge/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/spark/anaconda3/envs/lmforge/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Training time for deberta-xlarge: 5630.38 seconds

/home/spark/anaconda3/envs/lmforge/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/spark/anaconda3/envs/lmforge/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/spark/anaconda3/envs/lmforge/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/spark/anaconda3/envs/lmforge/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/spark/anaconda3/envs/lmforge/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/spark/anaconda3/envs/lmforge/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/spark/anaconda3/envs/lmforge/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Prediction time for deberta-xlarge: 94.38 seconds

Classification Report for deberta-xlarge:
              precision    recall  f1-score   support

           0     0.0000    0.0000    0.0000       160
           1     0.8707    1.0000    0.9309      1077

    accuracy                         0.8707      1237
   macro avg     0.4353    0.5000    0.4654      1237
weighted avg     0.7580    0.8707    0.8105      1237

{'model': 'deberta-xlarge', 'max_length': 256, 'train_time_sec': 5630.3785, 'pred_time_sec': 94.3806171875, 'accuracy': 0.8706548100242523, 'f1': 0.8104539588557645, 'precision': 0.7580397982183668, 'recall': 0.8706548100242523}

--- Training deberta-xlarge with max_length=512 ---

===== Training deberta-xlarge =====

Some weights of DebertaForSequenceClassification were not initialized from the model checkpoint at microsoft/deberta-xlarge and are newly initialized: ['classifier.bias', 'classifier.weight', 'pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Map:   0%|          | 0/4947 [00:00<?, ? examples/s]

Map:   0%|          | 0/1237 [00:00<?, ? examples/s]

/tmp/ipykernel_2580169/3185563332.py:4: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `WeightedLossTrainer.__init__`. Use `processing_class` instead.
  super().__init__(*args, **kwargs)

Training time for deberta-xlarge: 8753.06 seconds

Prediction time for deberta-xlarge: 219.72 seconds

Classification Report for deberta-xlarge:
              precision    recall  f1-score   support

           0     0.9400    0.8812    0.9097       160
           1     0.9825    0.9916    0.9871      1077

    accuracy                         0.9774      1237
   macro avg     0.9613    0.9364    0.9484      1237
weighted avg     0.9770    0.9774    0.9771      1237

{'model': 'deberta-xlarge', 'max_length': 512, 'train_time_sec': 8753.064, 'pred_time_sec': 219.719546875, 'accuracy': 0.9773645917542442, 'f1': 0.9770518044511045, 'precision': 0.977020851259725, 'recall': 0.9773645917542442}